version: '3.8'

volumes:
  mysql-volume:

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/dev/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./src/:/app:cached
    tty: true
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./.docker/dev/php/Dockerfile
    volumes:
      - ./src/:/app:cached
    tty: true
    environment:
      - APP_ENV=development
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./.docker/dev/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql